project:
  type: website
  output-dir: docs
website: 
  title: "Effekter av arealbruk og arealbruksendringer på biodiversitet, økosystemtjenester og karbonlagring i Norge" 
  navbar:
    right:
      - text: 'About'
        href: about.html
      - text: "Map"
        href: index.html