project:
  type: website
  output-dir: docs
website: 
  title: "Effekter av arealbruk og arealbruksendringer på biodiversitet, økosystemtjenester og karbonlagring i Norge" 
  navbar:
    right:
      - text: 'Oppsummering for beslutningstakere'
        href: index.html
      - text: "Datatabell"
        href: datatabell.html

