---
title: "Om prosjektet"
format: html
editor: visual
---

Dette prosjektet er finansiert av [Forskningsrådet](https://www.forskningsradet.no), via en korrdinerings- og støtteaktivitet. Mer informasjon om prosjektet finnes [her](https://prosjektbanken.forskningsradet.no/project/FORISS/338270?Kilde=FORISS&distribution=Ar&chart=bar&calcType=projects&Sprak=no&sortBy=score&sortOrder=desc&resultCount=30&offset=0&Fritekst=arealbruk).

Hovedmålet med dette prosjektet er å gi en helhetlig oversikt over tilgjengelig kunnskap knyttet til effekter av arealbruk og arealbruksendringer på norsk natur, med fokus på biologisk mangfold, økosystemtjenester, klimatilpasning, karbonbinding og lagring. Kartet er begrenset i geografisk omfang til Norge, Sverige og Finland (se inklusjonskriterier nedenfor). Rapporten er dessuten ledsaget av et beslutningsstøtteverktøy som en utvidelse av det systematiske kartet for å kontekstualisere tilgjengelig kunnskap. Verktøyet er utformet som en konseptuell modell av kunnskapsfeltet og synliggjøre betydningen av kunnskapshull på ulike områder.

De viktigste forskningssprøsmålene vi dekker i vårt systematiske kart er 1) *Hvilken forskningsbasert kunnskap finnes om virkningene av arealbruk og endringer i arealbruk på biologisk mangfold, økosystemtjenester og karbonbinding i Norge*, 2) *hvilken type konflikter er identifisert mellom ulike former for arealbruk*, og 3) *hvilke verktøy foreslås for å forbedre styringen*.
